### PR TITLE
fix broken formatting

### PR DESCRIPTION
**Pull request by MatthiasWinzeler**
looks like some merge screwed up the formatting, this fixes it.

### CODE REVIEW

**Review by xenophenes — COMMENTED** [review]
Thanks for catching this! Are you also able to re-generate the documentation using the ./generate-docs.sh script in $CCPROOT? That will fix the forward-facing documentation website. If not, no worries - I can submit a follow-up PR handling that aspect.

**Comment by xenophenes** [comment]
@jmccormick2001 @cahoonpwork FYI, this should be ready to merge. 

@MatthiasWinzeler Thanks for generating the docs!

**Comment by xenophenes** [comment]
Actually, as @jasonodonnell pointed out, this is being submitted to the **master** branch. @MatthiasWinzeler, one last request - would you mind resubmitting to the **develop** branch to avoid future merge conflicts? Thanks!

**Comment by jmccormick2001** [comment]
lets re-do this against the develop branch, master branch is not accepting any PRs at this point.

**Pull request closed without merging**
