### PR TITLE
Issues #420, #440, #441, #439

### PR DESCRIPTION
**Pull request by xenophenes**
- replaced hard coded crunchydata/ in all run scripts (pull-from-dockerhub.sh, push-from-dockerhub.sh, etc)
- replaced hard coded crunchydata/ in all JSON files
- added arguments to processing commands (such as oc process -f) to process that variable
- tested the following examples in the following environments after changes:

https://docs.google.com/spreadsheets/d/1iG8nHZUDbO91K-sF6HUuM0CDLxbf62rva2c61i-2-JY/edit?usp=sharing

### CODE REVIEW

**Comment by xenophenes** [comment]
Issues #439 #440 #441 all taken care of with three additional commits to this branch. 

- Locations updated from /pg_xlog to /pg_wal
- Functions changed from pg_xlog_replay_resume(); -> pg_wal_replay_resume();
- run-restore-pitr.sh was referencing incorrect wal directory, changed reference
- Docs were referencing wrong directory for checking wal, changed reference
- Added example output where it was indicated but not present to the docs

Tested on Docker with rebuilt images on a clean machine. Double checked the process and all logs.

**Review by abrightwell — COMMENTED** [review]
Seems that we'd probably want to check the version first and use `wal` vs `xlog` based on that. Otherwise, pre-pg10 versions will no longer work.

I suppose this could be accomplished a couple of different ways:

1) If you have access to the data directory (which looks like most of these cases do), then checking `PG_VERSION`.

2) `psql -c "SELECT version();"`

**Comment by xenophenes** [comment]
OK; I'll take a look at updating these commits to take that into account.

**Comment by xenophenes** [comment]
Taken into account. Thanks @davecramer for the helpful input!

**Comment by jmccormick2001** [comment]
please pull out the simple stuff from the PR like CCP_IMAGE_PREFIX changes from the xlog/wal changes into separate PRs so I can better review/test them, they seem to be 2 different Issues here.  thanks.

**Pull request closed without merging**
