### PR TITLE
xq_crunchy-containers-296: Use HOSTNAME env instead of using localhost for liveness check and readiness check. 

### PR DESCRIPTION
**Pull request by xqianwang**

### CODE REVIEW

**Comment by xqianwang** [comment]
In some cases, /etc/resolve.conf doesn't include 127.0.0.1 as localhost, but kubernetes(openshift) does provide HOSTNAME env for each pod.

**Comment by xenophenes** [comment]
Hello! This PR is reviewed and looks great; I'd just like to ask that you remove the commit #296: Liveness and Readiness checks should use PG_DATABASE - as was mentioned on that previous commit by Jeff:

> thanks, but having the value default to 'postgres' make sense for almost all situations that I can think of, please elaborate on how this is useful and I'll reconsider..regards.

Once that commit is removed, let us know and we'll go ahead and merge this in. Thank you!

**Comment by xqianwang** [comment]
OK, I am going to remove commit #296, thanks!

**Comment by xqianwang** [comment]
Hi @xenophenes I have closed this pr and created another PR for this. https://github.com/CrunchyData/crunchy-containers/pull/306, thanks!

**Comment by xenophenes** [comment]
Thanks, looks great!

**Pull request closed without merging**
